name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UtilityFunctions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --logger trx --results-directory TestResults
        working-directory: UtilityFunction.Tests/

      - name: Build the project
        run: dotnet build --configuration Release
        working-directory: UtilityFunctions

      - name: Pack the project
        run: dotnet pack --configuration Release --output ./nupkgs

      #- name: Publish to NuGet
      #  env:
      #    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      #  run: dotnet nuget push ./nupkgs/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
    